language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]
    then
      rustup component add rustfmt
      cargo fmt --all -- --check
    fi
  - |
    rustc --version &&
    cargo test --all-features
matrix:
  allow_failures:
    - rust: nightly
