language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
before_cache:
  - rm -rf /home/travis/.cargo/registry
script:
  - |
    rustc --version &&
    cargo test --all-features
matrix:
  allow_failures:
    - rust: nightly
