[workspace]
members = [
    "itconfig",
    "itconfig_tests",
    "examples/diesel",
    "examples/rocket", # nightly
    "examples/hyper",
]

default-members = [
    "itconfig",
    "itconfig_tests",
]
